# Old solarize workaround
set -g default-terminal "screen-256color"

# Decrease window switch delay
set -sg escape-time 0

# Mood dependent history option
set-option -g history-limit 3000

# split panes using '|' and '-' because more intuitive
bind \ split-window -h
bind - split-window -v
unbind '"'
unbind %

# source ~/.tmux.conf
bind r source-file ~/.tmux.conf

# mouse mode for scrolling
set -g mouse off
