# ~/.tmux.conf

# change prefix
set -g prefix C-a
bind C-a send-prefix -2

# boost history limit
set -g history-limit 5000

# Old solarize workaround
# set -g default-terminal "screen-256color"

# Decrease window switch delay
set -sg escape-time 0

# Mood dependent history option
set-option -g history-limit 3000

# split panes using '|' and '-' because more intuitive
# Must escape the \ because idk
bind \\ split-window -h
bind - split-window -v

# mouse mode for scrolling
set -g mouse off

# reload config
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# new window
bind N new-window

# navigation (vim)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

